[build]
  command = "cross-env GENERATE_SOURCEMAP=false DISABLE_ESLINT_PLUGIN=true INLINE_RUNTIME_CHUNK=false CI=false NODE_OPTIONS=--max-old-space-size=6144 react-scripts build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  INLINE_RUNTIME_CHUNK = "false"
  CI = "false"
  NODE_OPTIONS = "--max-old-space-size=6144"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
